### ISSUE TITLE
Qwen没有明显提速

### ISSUE THREAD

**Issue by chaos0625** [pkunlp-icler/FastV#10]
将src/transformers/src/transformers/models/llama/modeling_llama.py文件中，与fastv相关的代码，写到了modeling_qwen2.py中以后，进行测试。k=3，r=0.75时，仅有略微的提速；k=2，r=0.5时，速度甚至比不用fastv更慢。请问是什么原因呢？能否提供一个qwen的demo？

**Comment by chaos0625** [comment]
测试时，设置的FASTV_INPLACE=False，如果FASTV_INPLACE=True，cuda会报错...

**Comment by chenllliang** [comment]
你好，FASTV_INPLACE=False 时是基于修改 attention mask 进行的模拟token pruning，实际计算量不变。 FASTV_INPLACE=True 的时候，才是真实丢弃tokens，有计算量的减少，会有明显提速，可以参考llava。Qwen相关demo开源正在准备中。

**Comment by testpppppp** [comment]
@chaos0625 请问最后测试提速了多少

**Comment by xyfore** [comment]
请问您是怎么修改modeling_qwen2.py @chaos0625

**Comment by cccccs** [comment]
> 请问您是怎么修改modeling_qwen2.py [@chaos0625](https://github.com/chaos0625)

请问你修改成功了吗 @xyfore
