### ISSUE TITLE
FileNotFoundError: Couldn't find a dataset script at /cpfs01/shared/public/cl/datasets/OCR-VQA/OCR-VQA.py or any data file in the same directory

### ISSUE THREAD

**Issue by zzzfffsss** [pkunlp-icler/FastV#11]
Thank you for your contribution. I encountered the problem "FileNotFoundError: Couldn't find a dataset script at /cpfs01/shared/public/cl/datasets/OCR-VQA/OCR-VQA.py or any data file in the same directory" while running the command "bash ./src/FastV/inference/eval/eval_ocrvqa_fastv_token_mask.sh". Could you please make this part of the file open source?

**Comment by chenllliang** [comment]
Thanks for your attention, you could replace the path to "howard-hou/OCR-VQA" , which has been uploaded to huggingface dataset. We would correct that in time.

**Comment by zzzfffsss** [comment]
Thank you for your answer. Furthermore, I would like to know which is the implementation code of the FastV method described in the paper. Could you please tell me？

**Comment by chenllliang** [comment]
the implementation is here：

https://github.com/pkunlp-icler/FastV/blob/main/src/transformers/src/transformers/models/llama/modeling_llama.py#L730

Liang Chen
Peking University
________________________________
发件人: zzzfffsss ***@***.***>
发送时间: Thursday, April 11, 2024 12:15:59 AM
收件人: pkunlp-icler/FastV ***@***.***>
抄送: Liang Chen ***@***.***>; Comment ***@***.***>
主题: Re: [pkunlp-icler/FastV] FileNotFoundError: Couldn't find a dataset script at /cpfs01/shared/public/cl/datasets/OCR-VQA/OCR-VQA.py or any data file in the same directory (Issue #11)


Thank you for your answer. Furthermore, I would like to know which is the implementation code of the FastV method described in the paper. Could you please tell me？

―
