### ISSUE TITLE
Why llava-hf replaces llava?

### ISSUE THREAD

**Issue by FanshuoZeng** [pkunlp-icler/FastV#12]
Hello. I noticed that you used llava-hf instead of the original llava in the "Integrate FastV to LLM inference framework" section, and the transformers used have also changed. Can you tell me why this is happening? In other words why not continue to use the original environment or the difference between llava and llava-hf.
您好。我注意到您在“Integrate FastV to LLM inference framework”板块使用的llava-hf而不是原来的llava，并且使用的transformers也发生了改变。您可以告诉我为什么要这样吗？换句话说为什么不继续使用原来的环境或llava与llava-hf的区别。

**Comment by chenllliang** [comment]
Hi, we add llava-hf implementation for more friendly community usage since it's easier to use in the huggingface model. To reproduce the results from the paper, you could simply use the original llava verison of FastV.
