### ISSUE TITLE
FastV Inference and Evaluation

### ISSUE THREAD

**Issue by yueeryty** [pkunlp-icler/FastV#15]
In this section, I encountered AttributeError: 'Llava LlamaModel' object has no attribute 'reset_fastv'
After trying to modify the code, it was found that it was a modification to the model in Parser. add argument ('-- model path', type=str, required=True, default="/home/cl/models/lava v1.5-13b"), which was not found in the code. What modifications have been made to the model? Can the model be placed in the code？

**Comment by chenllliang** [comment]
Hi you could download the model from https://huggingface.co/liuhaotian/llava-v1.5-13b or https://huggingface.co/liuhaotian/llava-v1.5-7b.

Can you provide more information about when did the bug happen? Did you install the llava and transformers source code from our repo? We add the "reset_fastv" method to the original llama architecture as in https://github.com/pkunlp-icler/FastV/blob/cf91d095a99e7dfdaf82df0ab49966646c6efa27/src/transformers/src/transformers/models/llama/modeling_llama.py#L582
