### ISSUE TITLE
Why is sys-length equal to 36?

### ISSUE THREAD

**Issue by FanshuoZeng** [pkunlp-icler/FastV#16]
When I tried to evaluate the aokvqa data set, I found the system prompt: 'A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions. USER:' has a token length of 35 ( 0 to 34).

你好，我尝试评估aokvqa数据集的时候，发现系统提示：'A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions. USER:'的token长度为35（0到34）。

**Comment by mengqiDyangge** [comment]
我这里发现llava的训练代码里面的prompt经过tokenizer之后的长度好像也是35。

**Comment by chenllliang** [comment]
Thank you for your careful observation. We have also discovered that you can adjust the FAST_V_SYS_LENGTH to 35, which does not impact the results.
