### ISSUE TITLE
Question for transformers version

### ISSUE THREAD

**Issue by cswangxiaowei** [pkunlp-icler/FastV#20]
Hi I encountered the error: 
TypeError                                 Traceback (most recent call last)
[<ipython-input-6-edb2d3eccd42>](https://9p308ykg3ue-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240703-060140_RC00_649031487#) in <cell line: 21>()
     19 }
     20 
---> 21 model = LlavaForConditionalGeneration.from_pretrained(
     22     model_id,
     23     torch_dtype=torch.float16,

[/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py](https://9p308ykg3ue-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240703-060140_RC00_649031487#) in from_pretrained(cls, pretrained_model_name_or_path, config, cache_dir, ignore_mismatched_sizes, force_download, local_files_only, token, revision, use_safetensors, *model_args, **kwargs)
   3373         with ContextManagers(init_contexts):
   3374             # Let's make sure we don't run the init function of buffer modules
-> 3375             model = cls(config, *model_args, **model_kwargs)
   3376 
   3377         # make sure we use the model's config since the __init__ call might have copied it

TypeError: LlavaForConditionalGeneration.__init__() got an unexpected keyword argument 'fastv_config'

May I know which version of transformers is utilized for this experiment? I tried several versions but all failed. 

Thank you!

**Comment by chenllliang** [comment]
Hi, it seems that you are using the hf-version of llava. We change the source code for hf-version llava. You should install the transformers package from our repo, which is shown in https://github.com/pkunlp-icler/FastV?tab=readme-ov-file#support-huggingface-llava-model

**Comment by cswangxiaowei** [comment]
Thank you for the reply! 
I tried to install again but still faced a issue: 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-3-edb2d3eccd42>](https://p1yiosox69-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240703-060140_RC00_649031487#) in <cell line: 6>()
      4 
      5 import torch
----> 6 from transformers import AutoProcessor, LlavaForConditionalGeneration, TextStreamer
      7 
      8 model_id = "/content/drive/MyDrive/FastV/model"

ImportError: cannot import name 'LlavaForConditionalGeneration' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

May I know if I need to install llava from resource to solve this issue? (I used google colab A100). 
Thank you!

**Comment by chenllliang** [comment]
Can you show the result of `pip list` to check whether the `transformers` is from this repo? You need to follow https://github.com/pkunlp-icler/FastV?tab=readme-ov-file#support-huggingface-llava-model to install llava.

**Comment by cswangxiaowei** [comment]
I recreated a new virtual environment and solved the problem. Thanks for your help!
