### ISSUE TITLE
modeling_llama_fastv_kvcache.py

### ISSUE THREAD

**Issue by cool-xiang** [pkunlp-icler/FastV#21]
Thank you for your wonderful work! I noticed this code: modeling_llama_fastv_kvcache.py, This is for saving the full kv-caches of the visual token. Can this code run now? I see a few todos in the code line. 

Thank you very much!

**Comment by chenllliang** [comment]
Hi, this part of code is discarded and not tested, we choose to the huggingface's llava to implement kv-cache. For kv-cache, please refer to [this comment](https://github.com/pkunlp-icler/FastV/issues/14#issuecomment-2208160255) for more details.
