### ISSUE TITLE
fast_v is not enabled in demo.py

### ISSUE THREAD

**Issue by ThisisBillhe** [pkunlp-icler/FastV#25]
I notice that use_fast_v is set to false in L191-192 in demo.py and is not activated in model.reset_fastv() either.

**Comment by ThisisBillhe** [comment]
Also, can FastV support FlashAttention? In the case of long sequences, it will cause OOM.

**Comment by chenllliang** [comment]
Hi, the demo.py is used to plot attention map so it does not need to activate fastv

**Comment by chenllliang** [comment]
FastV has no conflicts with Flash-attention and they could be used together.

**Comment by ThisisBillhe** [comment]
To my best knowledge, attention scores are not accessible in FlashAttention. So how can we use FastV along with FlashAttention?

**Comment by chenllliang** [comment]
Fastv only computes filters the image token once. It means that you can adopt flash attention before and after the filtering layer. I think you dont need to compute the attention scores in flash attn.
