### ISSUE TITLE
[Feature] Use FastV with origin llava and transformer.

### ISSUE THREAD

**Issue by tzjtatata** [pkunlp-icler/FastV#3]
Thank you for the great work.
I notice that the directory src/ contains codes from transformer and llava. But the changes are not highlighted.

So can I use the original transformer and llava with FastV? If no, it will be too hard to use FastV in the new versions of llava or other models. The feature is actually very important in this day.

**Comment by chenllliang** [comment]
Hi, thanks for your advice. The main change of source code is in the forward function of LlamaModel from [modeling_llama.py](https://github.com/pkunlp-icler/FastV/blob/36e71e90c6c8cd5f5de97eebfc2727a83b261327/src/transformers/src/transformers/models/llama/modeling_llama.py) of transformers repo. 

We are now actively working on integrating FastV to transformers and vLLM framework to support more models. Stay tuned!

**Comment by tzjtatata** [comment]
Thanks for your helpful reply！



---Original---
From: "Liang ***@***.***&gt;
Date: Sun, Mar 17, 2024 19:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pkunlp-icler/FastV] [Feature] Use FastV with origin llava andtransformer. (Issue #3)




 
Hi, thanks for your advice. The main change of source code is in the forward function of LlamaModel from modeling_llama.py of transformers repo.
 
We are now actively working on integrating FastV to transformers and vLLM framework to support more models. Stay tuned!

**Comment by chenllliang** [comment]
We add the latency experiment in https://github.com/pkunlp-icler/FastV/blob/main/README.md#latency-experiment-reproduction. Hope it helps.

**Comment by tzjtatata** [comment]
Thank you!
