### ISSUE TITLE
Question About Text-Image Attn Maps

### ISSUE THREAD

**Issue by Luo-Z13** [pkunlp-icler/FastV#33]
Hello, have you tried visualizing the attention heatmaps of the first 4 layers in `LlamaDecoderLayer` for the same image using different text prompts? I only extracted the part of the attention matrix where text tokens attend to image tokens, reshaped it into a 2D heatmap, and plotted it. I found that the heatmaps generated by different text prompts are almost identical. Is this a normal phenomenon?

**Comment by chenllliang** [comment]
Hi, I think it is normal if they are not completely identical.
