### ISSUE TITLE
开源的只是llva请问什么时候可以开源qwen的Demo呢

### ISSUE THREAD

**Issue by Cristhine** [pkunlp-icler/FastV#4]
希望可以开源qwen的用法

**Comment by chenllliang** [comment]
目前正在将FastV集成到Transformers的generate函数里，届时会支持不同vllm，stay tuned!

**Comment by lzy37ld** [comment]
@chenllliang 请问为什么是利用attention score而不是saliency score in (https://arxiv.org/pdf/2305.14160.pdf)

**Comment by chenllliang** [comment]
saliency score需要反向传播求导才能计算，fastv是在前向传播过程中就进行的token裁剪。

Liang Chen
Peking University
________________________________
发件人: lzy37ld ***@***.***>
发送时间: Friday, April 5, 2024 2:00:56 PM
收件人: pkunlp-icler/FastV ***@***.***>
抄送: Liang Chen ***@***.***>; Mention ***@***.***>
主题: Re: [pkunlp-icler/FastV] 开源的只是llva请问什么时候可以开源qwen的Demo呢 (Issue #4)


@chenllliang<https://github.com/chenllliang> 请问为什么是利用attention score而不是saliency score in (https://arxiv.org/pdf/2305.14160.pdf)

―

**Comment by XuRui314** [comment]
请问vllm的集成现在已经实现了吗
