### ISSUE TITLE
Still I dont know why this method can reduce flops after reading code

### ISSUE THREAD

**Issue by KonstnarK** [pkunlp-icler/FastV#5]
I've read the fastV code in https://github.com/pkunlp-icler/FastV/blob/36e71e90c6c8cd5f5de97eebfc2727a83b261327/src/transformers/src/transformers/models/llama/modeling_llama.py

The code only mask trivial img tokens on attention mask, which wont reduce any attention computation.  Is there any code change  I have not noticed

**Comment by chenllliang** [comment]
Sorry I put a wrong code link in the readme, please refer to https://github.com/pkunlp-icler/FastV/blob/45d47009ed321915662b08f0aeb17a66564b722c/src/transformers/src/transformers/models/llama/modeling_llama.py#L730   .   The FASTV_INPLACE method actually drop the hidden states of pruned image tokens.
