### ISSUE TITLE
请问当我要评估aokvqa的时候 数据集文件的格式是要什么样的，文件的存放位置是什么样的

### ISSUE THREAD

**Issue by Lyn-Lucy** [pkunlp-icler/FastV#6]

**Comment by chenllliang** [comment]
你好，理论上hf格式的数据已经传到github上来了，不需要额外做数据处理。请问你报了什么错呢

**Comment by Lyn-Lucy** [comment]
raise FileNotFoundError(
FileNotFoundError: Directory ./data/aokvqa is neither a `Dataset` directory nor a `DatasetDict` directory.
我是克隆之后修改了模型路径然后直接 运行bash ./src/FastV/inference/eval/eval_aokvqa_latency_fastv_inplace.sh
FastV/data/aokvqa/validation/data-00000-of-00001.arrow 这个地方是只有这个文件吗 看代码他是缺少dataset_info.json类似这种的文件

**Comment by chenllliang** [comment]
了解了 看来是少了文件  今天晚些时候会把完整dataset更新上来

**Comment by Lyn-Lucy** [comment]
谢谢！

**Comment by HaozheZhao** [comment]
> 谢谢！


The file `dataset_info.json` is now successfully uploaded to GitHub.

**Comment by chenllliang** [comment]
请问问题解决了吗 @Lyn-Lucy

**Comment by Lyn-Lucy** [comment]
谢谢可以了 但是需要把FastV/src/FastV/inference/eval/inference_aokvqa.py文件中
dataset = load_from_disk("./data/aokvqa/validation")

# valid_images = dataset["validation"]["image"]
# valid_questions = dataset["validation"]["question"]
# valid_choices = dataset["validation"]["choices"]
# valid_anwser = dataset["validation"]["correct_choice_idx"]

valid_images = dataset["image"]
valid_questions = dataset["question"]
valid_choices = dataset["choices"]
valid_anwser = dataset["correct_choice_idx"]
这部分内容改成这样，因为会提示KeyError: "Column validation not in the dataset. Current columns in the dataset: ['split', 'image_id', 'question_id', 'question', 'choices', 'correct_choice_idx',没有validation这个key

**Comment by Lyn-Lucy** [comment]
谢谢可以了 但是需要把FastV/src/FastV/inference/eval/inference_aokvqa.py文件中
dataset = load_from_disk("./data/aokvqa/validation")

valid_images = dataset["image"]
valid_questions = dataset["question"]
valid_choices = dataset["choices"]
valid_anwser = dataset["correct_choice_idx"]
这部分内容改成这样，因为会提示KeyError: "Column validation not in the dataset. Current columns in the dataset: ['split', 'image_id', 'question_id', 'question', 'choices', 'correct_choice_idx',没有validation这个key
